name: Maven Verify

on:
  push:
    branches: [ "main" ]

jobs:
  maven:
    name: Maven Verify
    uses: backbase/workflows/.github/workflows/maven-verify.yml@v0.1.0
    secrets:
      maven-username: ${{ secrets.MAVEN_USERNAME }}
      maven-password: ${{ secrets.MAVEN_PASSWORD }}
#  release:
#    name: Docker Release
#    uses: backbase/workflows/.github/workflows/maven-docker-release.yml@v0.1.0
#    with:
#      version: ${GITHUB_REF##*v}
#    secrets:
#      github-token: ${{ secrets.GITHUB_TOKEN }}
#      maven-username: ${{ secrets.MAVEN_USERNAME }}
#      maven-password: ${{ secrets.MAVEN_PASSWORD }}