# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  maven-build-and-verify:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        name: Set up JDK 21
        with:
          java-version: '21'
          distribution: 'adopt'
      - uses: s4u/maven-settings-action@v2.4.1
        name: Set settings.xml
        with:
          servers: |
            [{
                "id": "backbase",
                "username": "${{ secrets.REPO_USERNAME }}",
                "password": "${{ secrets.REPO_PASSWORD }}"
            }]
      - run: mvn clean install
        name: Build and test project
